### ISSUE TITLE
Help with HA Energy Tab

### ISSUE THREAD

**Issue by slovely** [muppet3000/homeassistant-grott#81]
Hi, sorry if this is the wrong place for a query.

I've got your integration working - at least, the sensors have values that match the growatt app.

However, what I don't understand is the "Energy" tab on the sensors that I'd expect to use don't appear.  E.g. for Export To Grid, on the energy config page pressing 'Add Return' presents this:

![image](https://github.com/muppet3000/homeassistant-grott/assets/692489/34d3a4e0-4f97-433b-99ed-546315d0d470)

However, the entity I'd export to use for that is `sensor.ouctXXXXXX_export_to_grid_power` but it doesn't appear in the list.  I _think_ that is because the unit is Watts, and the dialog expects Wh/kWh.  That doesn't make sense to me as I am not exporting kWh, I'm exporting kW.

Even the graphic in the energy tab seems wrong to me:
![image](https://github.com/muppet3000/homeassistant-grott/assets/692489/1213ed59-79c4-44cd-8601-f2529142027f)

These values should be Watts/kW surely?  If not, which sensors should I map to the energy tab configuration?

Thanks very much!  Please let me know if I can help or need to provide more information.

**Comment by muppet3000** [comment]
Hi @slovely - No problem discussing this here, in fact it should probably be something that goes into an FAQ at some point.

This isn't an issue specific to my integration, this is the same for all energy monitoring in Home Assistant. Let me attempt to explain this in the best way I can (it took my quite a while to get my head around when they first introduced it as well).

- Home Assistant's energy dashboard does not work in 'current' values, it does everything in actual values.
- This means that you need to provide everything in terms of Wh or kWh. Buy WHY????
- Excellent question!!! It's simply because calculating the 'actual' values from the power values is really difficult because there's no way of determining how long it was operating at that power level, you have to make a lot of assumptions etc.
- Instead, Home Assistant works by calculating the rate based on the increase in value of Wh/kWh over time, it's much easier to say between X time and Y time Z amount of kWh was imported/exported and therefore it was done at R rate than trying to calculate how much was imported/exported from 100 rate snapshots in the same time period.
- Therefore, instead of looking at the energy distribution graph (the second image you posted) as a live-time view, think of it as an aggregated view over the entire day (or selected time period).

Once you wrap your head around that it all makes sense, basically "it's hard" is the short answer.

What I'd absolutely love though is the ability to reuse the above widget to display the live-time view in W/kW if you have the sensors available because that looks really nice on a dashboard (one of the few things I like about the growatt website/app).

Hope that answers your question, let me know if there's anything else I can explain for you.

Sidenote - I recommend using the 'lifetime/total' values wherever possible on that energy dashboard over the 'today' ones, the 'today' ones occasionally fluctuate and it causes the graphs to go a bit mental. I've never seen the same issues with the 'lifetime/total' values.

**Comment by muppet3000** [comment]
I made myself a little dashboard like this:
![image](https://github.com/muppet3000/homeassistant-grott/assets/10612068/22ce6dbd-1f19-43ce-928d-bf96dd5b368b)

I'd like to see if I can repurpose that widget though, it would look really cool.
